name: OpenConfig integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Check out public repo
      uses: actions/checkout@v6
      with: 
        repository: openconfig/public
        path: public

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel virtualenv pyang
        sudo apt-get update
        sudo apt-get install libxml2-dev libxslt1-dev

    - name: Run packaging test
      run: tests/packaging.sh

    - name: Generate test script
      run: |
         cd ${GITHUB_WORKSPACE}/tests/integration
         go get
         go build ${GITHUB_WORKSPACE}/tests/integration/gen.go 
         ${GITHUB_WORKSPACE}/tests/integration/integration -path ${GITHUB_WORKSPACE}/public > ${GITHUB_WORKSPACE}/run.sh

    - name: Run integration test
      run: |
         ${GITHUB_WORKSPACE}/run.sh
